---
title: "Flexdashboard for p8105_hw4_co2554"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: simplex
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
library(viridis)

data("ny_noaa")

ny_noaa =
  ny_noaa |>
  mutate(name = recode(id, 
                      "USW00094728" = "Central_Park", 
                      "USW00014733" = "Buffalo",
                      "USC00308746" = "Tupper_Lake_Sunmount"), 
         tmin = as.numeric(tmin) / 10, 
         tmax = as.numeric(tmax) / 10, 
         prcp = (prcp) / 10
         ) |>
  filter(
         year(date) == 2005,
         name %in% c("Central_Park", "Buffalo", "Tupper_Lake_Sunmount"),
         if_all(c(prcp, snow, snwd, tmax, tmin), ~!is.na(.))) |>
  select(name, date, prcp, snow, snwd, tmax, tmin)

```

This is my flex dashboard! :) 

Column {data-width=650}
-----------------------------------------------------------------------

### Density Plot

```{r density, message = FALSE}
ny_noaa |>
  select(name, tmax, tmin) |> 
  pivot_longer(
    tmax:tmin,
    names_to = "observation",
    values_to = "temp") |> 
plot_ly(x = ~temp, color = ~name, colors = viridis(3), type = "histogram", histnorm = "probability density") |> 
  layout(
    xaxis = list(title = "Temperature (°C)"),
    yaxis = list(title = "Density"),
    title = "Distribution of Temperature (2005)",
    showlegend = TRUE
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Precipitation Plot

```{r precipitation, message = FALSE}
ny_noaa |> 
  select(name, prcp, snow) |> 
  plot_ly(x = ~name) |> 
  add_bars(y = ~prcp, name = "Rainfall", marker = list(color = ~viridisLite::viridis(2)[1])) |> 
  add_bars(y = ~snow, name = "Snowfall", marker = list(color = ~viridisLite::viridis(2)[2])) |> 
  layout(
    title = "Annual Precipitation (2005)",
    xaxis = list(
      title = "Location"),
    yaxis = list(title = "Amount (mm)"),
    barmode = "group"
  )
```

### Scatterplot

```{r scatter, message = FALSE}
ny_noaa |>
  select(snow, snwd, name) |>
  plot_ly(x = ~snow, y = ~snwd, color = ~name, type = "scatter", mode = "markers", colors = "viridis" ) |>
  layout(
    title = "Snow vs. Snow Depth (2005)",
    xaxis = list(title = "Snowfall (mm)"),
    yaxis = list(title = "Snow Depth (mm)"),
    showlegend = TRUE)
```

